/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import AIPlayerController from "./scripts/AIPlayerController"
import MyplayerController from "./scripts/MyplayerController"
import ScorePanel from "./scripts/ScorePanel"
import BallHandle from "./scripts/BallHandle"
import GameManager from "./scripts/GameManager"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("scripts/AIPlayerController.js",AIPlayerController);
		reg("scripts/MyplayerController.js",MyplayerController);
		reg("scripts/ScorePanel.js",ScorePanel);
		reg("scripts/BallHandle.js",BallHandle);
		reg("scripts/GameManager.js",GameManager);
    }
}
GameConfig.width = 1920;
GameConfig.height = 1080;
GameConfig.scaleMode ="showall";
GameConfig.screenMode = "none";
GameConfig.alignV = "middle";
GameConfig.alignH = "center";
GameConfig.startScene = "Main.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
